name: Run Tetris Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tetris:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements file found"

      - name: Run Tetris Script
        run: python Tetris.py
